sudo: required
language: python
services:
  - docker

env:
  COMPOSE_VERSION: 1.22.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build
  - find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | echo
  - flake8 .
  - pylint --enable=E --disable=W,R,C --unsafe-load-any-extension=y app/ tests/ utils/ configuration/
  - bandit -r --exclude .venv -ll .
  - export CI_ENVIRONMENT=Yes && docker-compose run -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID web ./devops/scripts/run_test.sh
