version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./devops/docker/Nginx.Dockerfile
    links:
      - web:web
    volumes:
      - ./:/usr/src/app
    depends_on:
      - web
    ports:
      - 80:80

  web:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile
    depends_on:
      - rabbitmq
      - db
    command: bash -c "./devops/scripts/wait-for-it.sh -t 120 db:5432 && ./devops/scripts/start.sh env=development"
    environment:
      - ENVIRONMENT=development
      - DB_USER=messaging-service
      - DB_PASS=P@55w0rd
      - DB_NAME=messaging-service
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./:/usr/src/app
      - /app/static
      - /var/log
      - /var/log/nginx
    ports:
      - 80
    links:
      - rabbitmq:rabbitmq
      - db:db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # we forward this port because it's useful for debugging
      - 15672:15672  # here, we can access rabbitmq management plugin

  db:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=messaging-service
      - POSTGRES_USER=messaging-service
      - POSTGRES_PASSWORD=P@55w0rd

  redis:
    image: redis:3.2.10-alpine
    ports:
      - 6379:6379

  smpp-simulator:
    image: komuw/smpp_server:v0.2
    ports:
      - 2775:2775
      - 8884:8884

  swagger-ui:
    build:
      context: .
      dockerfile: ./devops/docker/SwaggerUI.Dockerfile
    environment:
      - FOLDER=./docs/api/swagger
      - SWAGGER_JSON=/docs/api/swagger/swagger/send-message.yml
      - API_URL=http://localhost:9001/docs/api/swagger/send-message-1.0.yml
    ports:
      - 9001:8080
    volumes:
      - ./docs/api/swagger:/docs/api/swagger
