version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./devops/docker/Nginx.Dockerfile
    links:
      - web:web
    volumes:
      - ./:/usr/src/app
    depends_on:
      - web
    ports:
      - 80:80

  web:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile
    depends_on:
      - rabbitmq
      - db
    command: bash -c "./devops/scripts/wait-for-it.sh -t 120 db:5432 && ./devops/scripts/app_server.sh env=development"
    environment:
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=configuration.settings
      - SERVICE=messaging-service
      - DB_USER=messaging-service
      - DB_PASS=P@55w0rd
      - DB_NAME=messaging-service
      - DB_HOST=db
      - DB_PORT=5432
      - HTTPBIN_URL=http://httpbin:8000
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - GCLOUD_PROJECT=pycon-monitoring-workshop
    volumes:
      - ./:/usr/src/app
      - /app/static
      - /var/log
      - /var/log/nginx
    ports:
      - 80
    links:
      - rabbitmq:rabbitmq
      - db:db
      - httpbin:httpbin

  worker:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile
    depends_on:
      - rabbitmq
      - db
    command: bash -c "./devops/scripts/wait-for-it.sh -t 120 db:5432 && ./devops/scripts/worker_server.sh"
    environment:
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=configuration.settings
      - SERVICE=messaging-service
      - DB_USER=messaging-service
      - DB_PASS=P@55w0rd
      - DB_NAME=messaging-service
      - DB_HOST=db
      - DB_PORT=5432
      - HTTPBIN_URL=http://httpbin:8000
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - GCLOUD_PROJECT=pycon-monitoring-workshop
    volumes:
      - ./:/usr/src/app
      - /app/static
      - /var/log
      - /var/log/nginx
    ports:
      - 80
    links:
      - rabbitmq:rabbitmq
      - db:db
      - httpbin:httpbin

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # we forward this port because it's useful for debugging
      - 15672:15672  # here, we can access rabbitmq management plugin

  db:
    image: postgres:9.5
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=messaging-service
      - POSTGRES_USER=messaging-service
      - POSTGRES_PASSWORD=P@55w0rd

  redis:
    image: redis:3.2.10-alpine
    ports:
      - 6379:6379

  smpp-simulator:
    image: komuw/smpp_server:v0.2
    ports:
      - 2775:2775
      - 8884:8884

  swagger-ui:
    build:
      context: .
      dockerfile: ./devops/docker/SwaggerUI.Dockerfile
    environment:
      - SWAGGER_HOST=${APP_DOMAIN:-localhost}:8080
      - API_URL=http://${APP_DOMAIN:-localhost}:${APP_PORT:-9001}/${FILE:-send-message}-1.0.yml
    ports:
      - 9001:8080
    volumes:
      - ./devops/scripts/swagger-ui-entrypoint.sh:/usr/share/nginx/swagger-ui-entrypoint.sh
      - ./docs/api/swagger:/usr/share/nginx/swagger

  httpbin:
    image: citizenstig/httpbin
    ports:
      - 8000:8000

  netdata:
    image: firehol/netdata
    container_name: netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
