swagger: '2.0'
info:
  description: Send message API
  version: 1.0
  title: Send message API
  termsOfService: ''
  contact:
    email: kevowahome@gmail.com
host: "<HOST>"
basePath: /api/messages/v1.0/
schemes:
  - https
  - http
paths:
  /sendMessage:
    post:
      tags:
        - sendMessage
      summary: Send a new message
      description: Send a new message
      operationId: sendMessage
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Submit message(s)
          schema:
            $ref: '#/definitions/SendMessageRequest'
      responses:
        '202':
          description: Message(s) accepted for onward submission
          schema:
            $ref: '#/definitions/SendMessageResponse'
        '400':
          description: Invalid input
definitions:
  SendMessageRequest:
    type: object
    required:
      - messageId
      - senderId
      - recipients
      - messageType
      - channel
      - message
    properties:
      messageId:
        type: string
        maxLength: 64
        example: "y7sdxl24df"
      senderId:
        type: string
        maxLength: 64
        example: "0700123456"
      recipients:
        type: array
        items:
          type: string
          maxLength: 64
          example: "0700987654"
      messageType:
        type: string
        enum: ['dummy', 'push', 'sms']
      channel:
        type: string
        enum: ['africas-talking', 'firebase', 'httpbin', 'smpp']
      message:
        type: string
        maxLength: 200
        example: This is an example message
      priority:
        type: string
        maxLength: 64
        example: 'normal'
      callback:
        type: string
        maxLength: 64
        example: 'https://mydomain.com/callback/y7sdxl24df'

  SendMessageResponse:
      type: object

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
