swagger: '2.0'
info:
  description: Send message API
  version: 1.0
  title: Send message API
  termsOfService: ''
  contact:
    email: kevowahome@gmail.com
host: "<HOST>"
basePath: /api/messages/v1.0/
schemes:
  - https
  - http
paths:
  /sendMessage:
    post:
      tags:
        - Send a new message
      summary: Send a new message
      description: Send a new message
      operationId: sendMessage
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: './common-1.0.yaml#/parameters/requestId'
        - $ref: './common-1.0.yaml#/parameters/timestamp'
        - name: body
          in: body
          description: Submit message(s)
          schema:
            $ref: '#/definitions/SendMessageRequest'
      responses:
        '202':
          description: Message(s) accepted for onward submission
          schema:
            $ref: '#/definitions/SendMessageResponse'
        '400':
          description: Invalid input
definitions:
  SendMessageRequest:
    type: object
    required:
      -
    properties:
      header:
        $ref: './common-1.0.yaml#/definitions/Header'

  SendMessageResponse:
      type: object
      required:
        - header
      properties:
        header:
           $ref: './common-1.0.yaml#/definitions/Header'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
